# Generated by Django 5.2.5 on 2025-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default='good dogs'),
            preserve_default=False,
        ),
    ]
