# Generated by Django 5.2.5 on 2025-08-18 11:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=cloudinary.models.CloudinaryField(default='null', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
